=== guitao/Game/resource/zh_cn/proto/Protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by MESMERiZE (MiZE) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="root">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="command" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>一组命令，value采用一个或多个单词，每个单词首字字母大写</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="param" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>一个条命令</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="attrib" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="value" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>命令名称，采用全大写单词，单词和单词之间用_隔开</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="path" use="required">
										<xs:annotation>
											<xs:documentation>"C > S"是客户端发送给服务端,"C > S"是服务端发送给客户端</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="S > C"/>
												<xs:enumeration value="C > S"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="info" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>对此命令的说明</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="useless" type="xs:boolean" default="false">
										<xs:annotation>
											<xs:documentation>该命令是否无用，默认false</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="value" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>命令名称</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="obj" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="attrib" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="value" type="xs:string" use="required"/>
						<xs:attribute name="info" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>说明文字</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="attrib">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>一个变量名称，采用一个或多个单词，首字母小写，后面的每个单词首字字母大写</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="consts" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>枚举值，客户端用的</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="type" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>服务器数据类型</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="info" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>参数说明</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== guitao/Game/resource/zh_cn/proto/Protocol.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='Parser3.xsl'?>
<!--
文件格式定义：
====command 一组命令，value采用一个或多个单词，每个单词首字字母大写
========param 一个条命令
============value 命令名称，采用全大写单词，单词和单词之间用_隔开
============path "C > S"是客户端发送给服务端,"C > S"是服务端发送给客户端
============info 对此命令的说明
============attrib 一组数据格式
================value 一个变量名称，采用一个或多个单词，首字母小写，后面的每个单词首字字母大写
====================如果数据是一个数组，则在名称后加[]，例如FRIEND_LIST命令中的info[num]，
====================其中info为变量名，[]表示数组，num表示数组中的数值变量，这个num取自num变量
================type 服务器数据类型
================info 参数说明
-->
<root xsi:noNamespaceSchemaLocation="Protocol.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<command value="System">
		<param value="LOGIN" path="C > S" info="登录到登陆服">
			<attrib value="account" type="char[48]" info="用户账号"/>
			<attrib value="gameType" type="uint16_t" info="游戏平台类型 从1000开始"/>
			<attrib value="gameZone" type="uint32_t" info="游戏区 从1开始"/>
			<attrib value="netType" type="uint16_t" info="1:电信 2:网通"/>
		</param>
		<param value="LOGIN" path="S > C" info="登录到登陆服返回结果">
			<attrib value="result" type="uint8_t" info="结果 0成功,1维护 2未到开服时间 3网关未开"/>
			<attrib value="ip" type="char[32]" info="网关ip"/>
			<attrib value="port" type="uint16_t" info="网关端口"/>
		</param>
		<param value="LOGIN_GATE" path="C > S" info="登录到网关">
			<attrib value="accid" type="uint32_t" info="用户唯一ID"/>
			<attrib value="key" type="uint32_t" info="用户登录用key"/>
		</param>
		<param value="LOGIN_GATE" path="S > C" info="登录到网关返回结果">
			<attrib value="result" type="uint8_t" info="结果 1成功,2其他地方登录 3验证错误 4网关人数满 5版本号不对 6IP冻结 7无效key"/>
		</param>
	</command>
</root>

=== guitao/Game/resource/zh_cn/proto/ValueObject.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by Administrator (EMBRACE) -->
<!--
文件格式定义：
====obj 一个数据对象
========value 对象名称，采用一个或多个单词，每个单词首字字母大写,最后一个单词为Info
============attrib 对象的一组数据格式
================value 一个变量名称，采用一个或多个单词，首字母小写，后面的每个单词首字字母大写
====================如果数据是一个数组，则在名称后加[]，例如FRIEND_LIST命令中的info[num]，
====================其中info为变量名，[]表示数组，num表示数组中的数值变量，这个num取自num变量
================type 服务器数据类型
================info 参数说明
-->
<root xsi:noNamespaceSchemaLocation="Protocol.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<obj value="ServerInfo" info="服务器信息">
		<attrib value="serverID" type="uint16_t" info="服务器id"/>
		<attrib value="serverType" type="uint16_t" info="服务器类型"/>
		<attrib value="name" type="char[33]" info="名字"/>
		<attrib value="ip" type="char[33]" info="内网ip"/>
		<attrib value="port" type="uint16_t" info="内网端口"/>
		<attrib value="extip" type="char[33]" info="外网ip"/>
		<attrib value="extport" type="uint16_t" info="外网端口"/>
		<attrib value="netType" type="uint16_t" info="网络类型（1电信，2网通）"/>
		<attrib value="load" type="uint32_t" info="最大负载"/>
		<attrib value="inuse" type="uint32_t" info="当前负载"/>
	</obj>
</root>
